language: php

php:
    - 5.6

before_script:
    - phpenv config-add .travis-php.ini
    - phpenv rehash
    - mkdir -p build/logs
    - mkdir -p bin
    - travis_retry curl -s http://getcomposer.org/installer | php -- --install-dir=bin --filename=composer
    - travis_retry php bin/composer install --no-interaction

script:
    - bin/phpunit --verbose -c phpunit.travis.xml

after_script:
    - bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
    - bin/coveralls -vvv
