language: php

php:
  - 5.6

branches:
  only:
    - master

env:
  - SYMFONY_VERSION="2.6.*"
  - SYMFONY_VERSION="2.7.*@dev"

matrix:
  fast_finish: true
  allow_failures:
    env: SYMFONY_VERSION="2.7.*@dev"

notifications:
  slack:
    secure: fQJkH85f60YbHu0y3y7lptnouX3IULkX9f8wrEq4+SFI7n7Uy6RLRhz1wRioOR0gjRcX4dH+40ZZit3GpLB0M781cOwuBAcnobrU6coE8YdbFLrK/EFD/qXM/6RlwRik/3TA3ZX5C1WQfrBxnxq3jvuTFDplrXoxThS3lIl/KCo=

before_install:
  - sh .travis-build-igbinary.sh
  - sh .travis-build-memcached.sh
  - phpenv config-add .travis-php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - mkdir -p build/logs
  - mkdir -p bin

install:
  - travis_retry composer self-update
  - travis_retry composer clear-cache
  - travis_retry composer require symfony/symfony:${SYMFONY_VERSION} --no-interaction

before_script:
  - bin/mantle doctrine:database:create
  - bin/mantle doctrine:schema:create

script:
  - bin/phpunit --verbose --configuration phpunit.travis.xml

after_script:
  - bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
  - bin/coveralls -vvv
