language: php

notifications:
  slack:
    secure: HuIz/xcPEACJvah+/h5jX4JX8Z22wgK0ZBIwn/v1KDnbl3m62EdJAfGN3jvGD+n9njmYUOCjslLHAooAC1MNntUcB9D2PJAArjD3mb9e34VtSwZ7NMfHkHZSksuaWg+nEDJrFSChvxHBp03/4JoVWjJMM2cm1TdpOMR0a/eFY1s=

branches:
  except:
    - gh-pages

php:
  - 5.6
  - 5.5
  - hhvm
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly
        - php: 5.5

before_script:
  - travis_retry curl -s http://getcomposer.org/installer | php
  - travis_retry php composer.phar install --dev --no-interaction
  - mkdir -p build/logs

script:
  - bin/phpunit --verbose

after_script:
  - bin/ocular code-coverage:upload --format=php-clover phpunit.coverage.clover