Scribe\MantleBundle\Doctrine\Entity\Node\NodeRenderEngine:

    type: entity
    table: null
    repositoryClass: Scribe\MantleBundle\Doctrine\Repository\Node\NodeRenderEngineRepository

    id:

        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

    oneToMany:

        revisions:
            targetEntity: NodeRevision
            mappedBy:     renderEngine
