Scribe\MantleBundle\Doctrine\Entity\Icon\IconTemplate:

    type:            entity
    table:           MantleBundle_IconTemplate
    repositoryClass: Scribe\MantleBundle\Doctrine\Repository\Icon\IconTemplateRepository

    id:

        id:
            type: integer
            id:   true
            generator:
                strategy: AUTO

    fields:

        slug:
            type:     string
            length:   512
            nullable: false

        description:
            type:   string
            length: 100

        engine:
            type:   string
            length: 10

        template:
            type:   text

        priority:
            type:   integer

    manyToOne:

        family:
            targetEntity: IconFamily
            inversedBy:   templates
            joinColumn:
                name:              iconFamilyId
                referencedColumn:  id
