Scribe\MantleBundle\Doctrine\Entity\Route\Route:

    type:            entity
    table:           MantleBundle_Route
    repositoryClass: Scribe\MantleBundle\Doctrine\Repository\Route\RouteRepository

    id:

        id:
            type: integer
            id:   true
            generator:
                strategy: AUTO

    fields:

        name:
            type:   string
            length: 120

        parameters:
            type:     json_array
            nullable: true

        referenceType:
            type:     string
            length:   40
            nullable: true

        description:
            type:     string
            length:   400
            nullable: true
