Scribe\MantleBundle\Doctrine\Entity\Navigation\Navigation:

    type:            entity
    table:           MantleBundle_Navigation
    repositoryClass: Scribe\MantleBundle\Doctrine\Repository\Navigation\Navigation

    id:

        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

    fields:

        aliases:
            type:     json_array
            nullable: false

        name:
            type:     string
            length:   '510'
            nullable: false

        description:
            type:     text
            nullable: true

        attributes:
            type:     json_array
            nullable: false
