Scribe\MantleBundle\Doctrine\Entity\Asset\AssetType:
    type: entity
    table: null
    repositoryClass: Scribe\MantleBundle\Doctrine\Repository\Asset\AssetTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        element:
            type: string
            length: 255
        attributes:
            type: json_array
    oneToMany:
        assets:
            targetEntity: Asset
            mappedBy: assetType
    lifecycleCallbacks: {  }
