---
Scribe\MantleBundle\Doctrine\Entity\Icon\IconFamily:

    type            : entity
    options         :
        row_format  : DYNAMIC
        charset     : utf8mb4
        collate     : utf8mb4_unicode_ci
    table           : Mantle_Icon_Family
    repositoryClass : Scribe\MantleBundle\Doctrine\Repository\Icon\IconFamilyRepository

    id:

        id:
            type      : smallint
            id        : true
            options   :
                unsigned : true
            generator :
                strategy : AUTO

    fields:

        slug:
            type     : string
            length   : 512
            nullable : false

        version:
            type   : string
            length : 40

        url:
            type   : string
            length : 255

        name:
            type   : string
            length : 40

        prefix:
            type   : string
            length : 10

        requiredClasses:
            type     : json_array
            nullable : true

        optionalClasses:
            type     : json_array
            nullable : true

        attributes:
            type     : json_array
            nullable : true

    oneToMany:

        templates:
            targetEntity : IconTemplate
            mappedBy     : family
            orderBy      :
                priority : ASC

    manyToMany:

        icons:
            targetEntity : Icon
            mappedBy     : families

...
