Scribe\MantleBundle\Entity\IconTemplate:

    type:            entity
    table:           null
    repositoryClass: Scribe\MantleBundle\EntityRepository\IconTemplateRepository

    fields:

        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

        slug:
            type:   string
            length: 40

        description:
            type:   string
            length: 100

        variables:
            type:     json_array
            nullable: true

        engine:
            type:   string
            length: 10

        template:
            type:   string
            length: 400

        priority:
            type:   integer

    manyToOne:

        family:
            targetEntity: IconFamily
            inversedBy:   templates
            joinColumn:
                name:              iconFamilyId
                referencedColumn:  id
