Scribe\MantleBundle\Entity\IconFamily:

    type:            entity
    table:           null
    repositoryClass: Scribe\MantleBundle\EntityRepository\IconFamilyRepository

    fields:

        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

        name:
            type:   string
            length: 40

        prefix:
            type:   string
            length: 10

        requiredClasses:
            type: json_array

        optionalClasses:
            type: json_array
            nullable: true

        attributes:
            type: json_array
            nullable: true

    oneToMany:

        templates:
            targetEntity: IconTemplate
            mappedBy:     family
            orderBy:
                priority: ASC

    manyToMany:
        icons:
            targetEntity: Icon
            mappedBy:     families
