Scribe\MantleBundle\Doctrine\Entity\Navigation\NavigationItem:

    type:            entity
    charset:         utf8mb4
    collate:         utf8mb4_unicode_ci
    table:           MantleBundle_NavigationItem
    repositoryClass: Scribe\MantleBundle\Doctrine\Repository\Navigation\NavigationItemRepository

    id:

        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

    fields:

        name:
            type:     string
            length:   510
            nullable: false

        description:
            type:     text
            nullable: true

        weight:
            type: integer

        attributes:
            type: json_array

        restrictions:
            type: json_array

        restrictionsInverse:
            type: json_array

    oneToMany:

        children:
            targetEntity: NavigationItem
            mappedBy:     parent

    manyToOne:

        parent:
            targetEntity: NavigationItem
            inversedBy:   children
            joinColumn:   { name: parentId, referencedColumn: id }

        root:
            targetEntity: NavigationSet
            inversedBy:   children
            joinColumn:   { name: rootId, referencedColumn: id }

        route:
            targetEntity: Scribe\MantleBundle\Doctrine\Entity\Route\Route
            joinColumn:   { name: routeId, referencedColumn: id }
