Scribe\MantleBundle\Entity\NavMenuItem:

    type:            entity
    table:           null
    repositoryClass: Scribe\MantleBundle\EntityRepository\NavMenuItemRepository

    fields:

        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

        slug:
            type:     string
            length:   40
            nullable: true

        context:
            type:   string
            length: 40

        title:
            type:   string
            length: 40

        description:
            type:     string
            length:   200
            nullable: true

        icon:
            type:     string
            length:   40
            nullable: true

        weight:
            type:     integer
            nullable: true

        routeName:
            type:     string
            length:   85
            nullable: true

        routeParameters:
            type:     json_array
            nullable: true

        roleRestrictions:
            type:     json_array
            nullable: true

        reverseRoleRestrictions:
            type:     json_array
            nullable: true

        attrs:
            type:     json_array
            nullable: true

    oneToMany:

        subItems:
            targetEntity: NavMenuSubItem
            mappedBy:     parent
            orderBy:      { weight: ASC }

    lifecycleCallbacks: {  }
