Scribe\MantleBundle\Entity\NodeContextType:
    type: entity
    table: null
    repositoryClass: Scribe\MantleBundle\Entity\NodeContextTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        slug:
            type: string
            length: 255
        name:
            type: string
            length: 255
    oneToMany:
        nodes:
            targetEntity: Scribe\MantleBundle\Entity\Node
            mappedBy: context
    lifecycleCallbacks: {  }
