Scribe\MantleBundle\Entity\Node:
    type: entity
    table: null
    repositoryClass: Scribe\MantleBundle\Entity\NodeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locked:
            type: boolean
        createdOn:
            type: datetime
            column: created_on
        updatedOn:
            type: datetime
            column: updated_on
        slug:
            type: string
            length: 255
        title:
            type: string
            length: '500'
        weight:
            type: integer
    manyToOne:
        author:
            targetEntity: User
            inversedBy: nodes 
            joinColumn:
                name: authorId
                referenceColumn: id
        context:
            targetEntity: Scribe\MantleBundle\Entity\NodeContextType 
            inversedBy: nodes 
            joinColumn:
                name: nodeContextTypeId
                referenceColumn: id
    oneToOne:
        latestRevision:
            targetEntity: Scribe\MantleBundle\Entity\NodeRevision
            inversedBy: owningNode
            joinColumn:
                name: latestRevisionId
                referenceColumn: id
    oneToMany:
        revisions:
            targetEntity: Scribe\MantleBundle\Entity\NodeRevision
            mappedBy: node
    manyToMany:
        parents:
            targetEntity: Scribe\MantleBundle\Entity\Node 
            inversedBy:  children 
            joinTable:
                name: ParentNodeMapToChildNode 
                joinColumns:
                    parentNodeId:
                        referencedColumnId: id
                inverseJoinColumns:
                    childNodeId:
                        referencedColumnId: id
        children:
            targetEntity: Scribe\MantleBundle\Entity\Node
            mappedBy: parents
        containerNodeRevisions:
            targetEntity: Scribe\MantleBundle\Entity\NodeRevision
            mappedBy: embeddedNodes
    lifecycleCallbacks: {  }
