Scribe\MantleBundle\Entity\NodeRevision:
    type: entity
    table: null
    repositoryClass: Scribe\MantleBundle\Entity\NodeRevisionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdOn:
            type: datetime
            column: created_on
        content:
            type: text
    oneToOne:
        diff:
            targetEntity: Scribe\MantleBundle\Entity\NodeRevisionDiff
            mappedBy: nodeRevision
        owningNode:
            targetEntity: Scribe\MantleBundle\Entity\Node
            mappedBy: latestRevision
    manyToOne:
        author:
            targetEntity: Scribe\MantleBundle\Model\AuthorInterface 
            inversedBy: nodeRevisions
            joinColumn:
                name: authorId
                referenceColumn: id
        node:
            targetEntity: Scribe\MantleBundle\Entity\Node
            inversedBy: revisions
            joinColumn:
                name: nodeId
                referenceColumn: id
        renderEngine:
            targetEntity: Scribe\MantleBundle\Entity\NodeRenderEngine 
            inversedBy: revisions
            joinColumn:
                name: nodeRenderEngineId 
                referenceColumn: id
    manyToMany:
        embeddedNodes:
            targetEntity: Scribe\MantleBundle\Entity\Node 
            inversedBy:  containerNodeRevisions 
            joinTable:
                name: NodeRevisionMapToEmbeddedNode 
                joinColumns:
                    nodeRevisionId:
                        referencedColumnId: id
                inverseJoinColumns:
                    nodeId:
                        referencedColumnId: id
        embeddedAssets:
            targetEntity: Scribe\MantleBundle\Entity\Asset 
            inversedBy:  containerNodeRevisions 
            joinTable:
                name: NodeRevisionMapToAsset 
                joinColumns:
                    nodeRevisionId:
                        referencedColumnId: id
                inverseJoinColumns:
                    assetId:
                        referencedColumnId: id
    lifecycleCallbacks: {  }
