Scribe\MantleBundle\Entity\Node:
    type: entity
    table: null
    repositoryClass: Scribe\MantleBundle\EntityRepository\NodeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO 
    fields:
        locked:
            type: boolean
            nullable: true
        created_on:
            type: datetime
            column: created_on
            nullable: true
        updated_on:
            type: datetime
            column: updated_on
            nullable: true
        slug:
            type: string
            length: 255
        title:
            type: string
            length: '500'
        weight:
            type: integer
            nullable: true
        materializedPath:
            type: string
            nullable: true
    manyToOne:
        author:
            targetEntity: Scribe\MantleBundle\Model\AuthorInterface 
            inversedBy: nodes 
            joinColumn:
                name: authorId
                referenceColumn: id
        context:
            targetEntity: Scribe\MantleBundle\Entity\NodeContextType 
            inversedBy: nodes 
            joinColumn:
                name: nodeContextTypeId
                referenceColumn: id
    oneToOne:
        latestRevision:
            targetEntity: Scribe\MantleBundle\Entity\NodeRevision
            inversedBy: owningNode
            joinColumn:
                name: latestRevisionId
                referenceColumn: id
    oneToMany:
        revisions:
            targetEntity: Scribe\MantleBundle\Entity\NodeRevision
            mappedBy: node
    manyToMany:
        containerNodeRevisions:
            targetEntity: Scribe\MantleBundle\Entity\NodeRevision
            mappedBy: embeddedNodes
    lifecycleCallbacks: {  }
