Scribe\MantleBundle\Entity\ResponseSearchReplace:
    type: entity
    table: null
    repositoryClass: Scribe\MantleBundle\EntityRepository\ResponseSearchReplaceRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        k:
            type: string
            length: 255
        v:
            type: text
        re:
            type: boolean
    lifecycleCallbacks: {  }
